### ISSUE TITLE
Ability to use 24h instead of AM/PM

### ISSUE THREAD

**Issue by DynamicsNinja** [drivardxrm/TimePicker.PCF#10]
Option to select between 12 or 24 hours mode.

**Comment by drivardxrm** [comment]
Hi @DynamicsNinja ,

very good point.
I will include in the next release, there is also some plumbing work that I wanted to do for a while.
;)

**Comment by DynamicsNinja** [comment]
No worries, take your time 😉

**Comment by drivardxrm** [comment]
fixed in V1.0.0.7
There is anew parameter 'Display Type'
![image](https://user-images.githubusercontent.com/38399134/96064818-1cf1e500-0e66-11eb-9770-50e0302f1cd0.png)

![image](https://user-images.githubusercontent.com/38399134/96065151-49a5fc80-0e66-11eb-8cd3-d13475f1be97.png)

![image](https://user-images.githubusercontent.com/38399134/96065217-4e6ab080-0e66-11eb-9cb5-c56b5a7b70ba.png)

![image](https://user-images.githubusercontent.com/38399134/96065311-54609180-0e66-11eb-8fff-3deee5b51f3e.png)
